gzip on;
gzip_comp_level 5;
gzip_min_length 1024;
gzip_proxied any;
gzip_vary on;
gzip_types text/plain text/css text/html application/javascript text/javascript application/json application/xml image/svg+xml;

server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  index app.html;

  location / {
    try_files $uri $uri/ =404;
  }

  # cache imágenes/payloads
  location ~* \.(jpg|jpeg|png|webp|gif|js|json)$ {
    expires 7d;
    add_header Cache-Control "public, max-age=604800";
  }
}
